version: '3'
services:
  app:
    container_name: docker-fastapi
    image: api
    #build: .
    restart: always
    ports:
      - '80:80'
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - .:/app


  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    hostname: test_mongodb

    environment:
      - MONGO_INITDB_DATABASE=teste
      - MONGO_INITDB_ROOT_USERNAME=romulo
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_NON_ROOT_USERNAME=saas
      - MONGO_NON_ROOT_PASSWORD=secret

    volumes:
      - mongodbdata:/data/db
    command: [--auth]
    restart: always
volumes:
  mongodbdata:
